
 import Header from "@/app/components/layout/Header";
 import { columns, Payment } from "./columns"
 import { DataTable } from "./data-table"
 import { Plus } from "lucide-react";
 import { Button } from "@/app/components/ui/button"
 import { Input } from "@/app/components/ui/input"

 async function getData(): Promise<Payment[]> {
     // Fetch data from your API here.
         return [
                 {
                             id: "728ed52f",
                                         amount: 250,
                                                     status: "فشل",
                                                                 email: "محمد عبدالله بكير",
                                                                         },
                                                                                 {
                                                                                             id: "728ed52f",
                                                                                                         amount: 100,
                                                                                                                     status: "جاري المعالجه",
                                                                                                                                 email: "سالم احمد الصويل",
                                                                                                                                         },
                                                                                                                                                 {
                                                                                                                                                             id: "728ed52f",
                                                                                                                                                                         amount: 304,
                                                                                                                                                                                     status: "نجاح",
                                                                                                                                                                                                 email: "خالد حسن محمد",
                                                                                                                                                                                                         },
                                                                                                                                                                                                             ]
                                                                                                                                                                                                             }

                                                                                                                                                                                                             const SalesPage = async () => {
                                                                                                                                                                                                                 const data = await getData()
                                                                                                                                                                                                                     return (
                                                                                                                                                                                                                             <div className="mt-16 p-6">
                                                                                                                                                                                                                                         <div className="max-w-7xl mx-auto">
                                                                                                                                                                                                                                                         {/* Header */}
                                                                                                                                                                                                                                                                         <Header title="اداره المبيعات" desc="صفحة مخصصه لاداره عمليات المبيعات" />
                                                                                                                                                                                                                                                                                         {/* Content */}
                                                                                                                                                                                                                                                                                                         <div className="flex flex-col gap-4 p-2 bg-light dark:bg-dark-content rounded-lg border border-border1/30 dark:border-border1/7">
                                                                                                                                                                                                                                                                                                                             {/* Controls (duplicated) - search first then add button */}
                                                                                                                                                                                                                                                                                                                                                 <div className="flex justify-between gap-4 p-4 pb-2 items-center text-black/70 dark:text-light-text">
                                                                                                                                                                                                                                                                                                                                                                         <Input type="search" className="flex-1" placeholder="ابحث..." />
                                                                                                                                                                                                                                                                                                                                                                                                 <Button className="bg-primary1 hover:bg-primary-hover text-white">اضافة <Plus /></Button>
                                                                                                                                                                                                                                                                                                                                                                                                                     </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                         <div className="flex justify-between gap-4 p-4 pb-2 items-center text-black/70 dark:text-light-text">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <Input type="search" className="flex-1" placeholder="ابحث..." />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <Button className="bg-primary1 hover:bg-primary-hover text-white">اضافة <Plus /></Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <DataTable columns={columns} data={data} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         export default SalesPage;
