import type { Metadata } from "next";
import { Almarai } from "next/font/google";
import "./globals.css";

const cairo = Almarai({
  subsets: ["arabic"],
  weight: ["400", "700", "800", "300"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${cairo.className} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
